# Generated by Django 5.1.4 on 2025-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("food_type", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("donation_date", models.DateTimeField(auto_now_add=True)),
                ("is_claimed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FoodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_name", models.CharField(max_length=100)),
                ("food_type_needed", models.CharField(max_length=100)),
                ("quantity_needed", models.PositiveIntegerField()),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
            ],
        ),
    ]
