# Generated by Django 5.1.4 on 2025-02-05 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "waste_app",
            "0002_donation_request_wastetracking_delete_fooddonation_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donor_name",
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="food_type",
            field=models.CharField(max_length=100, verbose_name="Type of Food"),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_date",
            field=models.DateField(auto_now_add=True, verbose_name="Request Date"),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_quantity",
            field=models.PositiveIntegerField(verbose_name="Requested Quantity (kg)"),
        ),
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested by",
            ),
        ),
        migrations.AlterField(
            model_name="wastetracking",
            name="waste_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
